// Header file for the ColorMatch application
// This file is generated by the ColorMatch Application in Learn Mode

// calibration data
sensorData_FLEX sdBlack = { 0, 0, 0 };
sensorData_FLEX sdWhite = { 0, 0, 0 };

// Color Table for matching
typedef struct
{
  char    name[9];  // color name 8+nul
  colorData_FLEX rgb;    // RGB value
} colorTable;

colorTable ct[] =
{
  {"WHITE", {0, 0, 0} },
  {"BLACK", {0, 0, 0} },
  {"YELLOW", {0, 0, 0} },
  {"ORANGE", {0, 0, 0} },
  {"RED", {0, 0, 0} },
  {"GREEN", {0, 0, 0} },
  {"BLUE", {0, 0, 0} },
  {"BROWN", {0, 0, 0} },
};
	
